### ISSUE TITLE
HID principal crashes when using containers

### ISSUE THREAD

**Issue by cjdoucette** [AltraMayor/XIA-for-Linux#14]
**Description**:

When using the HID principal to send packets between containers, the code crashes in net/xia/ppal_hid/main.c:main_input_input().

The crash happens because apparently `skb->sk` is `NULL` when using containers, so the call to `sock_net(skb->sk)` passes a null pointer which is then dereferenced.

The line of code is here: https://github.com/AltraMayor/XIA-for-Linux/blob/xia/net/xia/ppal_hid/main.c#L355

This code was recently added as a part of this commit: https://github.com/AltraMayor/XIA-for-Linux/commit/169567639ddc03d6a5a255fe37c7bad29e42541d

I have not checked whether the other parts of the code in this commit cause a similar crash.

When testing the HID principal by sending packets between two VMs, this crash does not occur.

**Environment**:

```
xia@xia:~$ uname -r
4.5.0-rc7-xia
xia@xia:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

Last commit: `xia/u4id: remove call to sk_release_kernel`

**Steps to Reproduce Error**:

I was testing the net-eval scripts when I found this bug, the setup for which can be found here: https://github.com/AltraMayor/XIA-for-Linux/wiki/Forwarding-performance-evaluation#Experiment_Scripts

```
# Obtain net-eval scripts and build.
git clone https://github.com/cjdoucette/net-eval.git
cd net-eval
bash howto
cd exp
```

```
# Obtain necessary packages.
sudo apt-get install lxc ruby1.9.1 bridge-utils
sudo gem install netaddr 
```

```
# Setup experiments and run them.
sudo ruby1.9.1 ./net-eval-setup.rb 10 60 -xs
sudo ruby1.9.1 ./net-eval-run.rb
```

**Comment by AltraMayor** [comment]
Hi @cjdoucette,

main_input_input() handles packets that come from the network, so these packets should have no socket associated with them. I don't know how the VM case you mentioned actually works.

The solution is to replace line 355 as follows:

```
- return dst_output(sock_net(skb->sk), skb->sk, skb);
+ return dst_output(xdst_net(xdst), skb->sk, skb);
```

Could you test this solution? If works as expected, could you write a pull request for it?

Thank you for your detailed report, your report made it easy to understand the problem.

**Comment by cjdoucette** [comment]
This solution works -- thanks! I made a pull request as well.

The VM case is actually not equivalent and is not invoking this function, as you suspected.

**Comment by cjdoucette** [comment]
Actually, it seems that zFilter also has the same kind of problem here:

https://github.com/AltraMayor/XIA-for-Linux/blob/xia/net/xia/ppal_zf/main.c#L440

and possibly also here:

https://github.com/AltraMayor/XIA-for-Linux/blob/xia/net/xia/ppal_zf/main.c#L402

After adding `iarg->net` to those lines the code no longer crashes. I'll update the pull request once I'm able to get the zFilter experiment with containers to work correctly to make sure there's no other errors.

Do you see any other bugs from commit https://github.com/AltraMayor/XIA-for-Linux/commit/169567639ddc03d6a5a255fe37c7bad29e42541d? Possibly this:

https://github.com/AltraMayor/XIA-for-Linux/blob/xia/net/xia/route.c#L786

**Comment by AltraMayor** [comment]
I've reviewed commit https://github.com/AltraMayor/XIA-for-Linux/commit/169567639ddc03d6a5a255fe37c7bad29e42541d for this kind of bug, and I believe that you have already found all bugs.

You're right about the two cases of zFilter, xdst_def_hop_limit_input_method(), and on the use of `iarg->net` to fix the two cases of zFilter. My suggestion to fix xdst_def_hop_limit_input_method() is as follows:

```
+ struct xip_dst *xdst;

...

- return dst_output(sock_net(skb->sk), skb->sk, skb);
+ xdst = skb_xdst(skb);
+ BUG_ON(!xdst);
+ return dst_output(xdst_net(xdst), skb->sk, skb);
```

One could have written `xdst_net(skb_xdst(skb))`, but it makes the life of someone debugging harder if one of those functions fails.

I'm going to wait for your updated pull request.

**Comment by cjdoucette** [comment]
OK, I updated the pull request with the changes and tested it on the zFilter experiment. Everything seems to be working.

**Comment by AltraMayor** [comment]
Thank you. I just merged the pull request.
