### ISSUE TITLE
dead link to PhD thesis in wiki

### ISSUE THREAD

**Issue by wattux** [AltraMayor/XIA-for-Linux#24]
Hey there, 

I noticed the [link of the PhD thesis *Linux XIA: An Interoperable Meta Network Architecture*](https://drive.google.com/file/d/0B7rBS9DPmw4AWWZQOUJhV2xDV3M/edit?usp=sharing) inside the [Wiki](https://github.com/AltraMayor/XIA-for-Linux/wiki#Whats_Linux_XIA) is not valid anymore.

**Comment by AltraMayor** [comment]
Thank you for pointing that out. I just fixed the link.
