### ISSUE TITLE
Kernel Compiling Error

### ISSUE THREAD

**Issue by BigQNo2** [AltraMayor/XIA-for-Linux#7]
#### Description:

when kernel compiling, if choose XIA stack not as optional modules (select with [*] rather than <M>) along with IPv4 stack in kernel configuration, there will jump out a multiple definition error. Otherwise, If selecting XIA stack as optional modules, kernel compiling will success. 
#### How to reproduce:

Following steps in wiki except for selecting XIA stack as default:

```
1. $ make nconfig
2. Select the XIA stack in configuration
```

![xia_stack](https://cloud.githubusercontent.com/assets/7075154/5001402/51199f60-69c3-11e4-9b56-0a4b0bc8c862.png)

```
3. $ make prepare
4. $ sed -rie 's/echo "\+"/#echo "\+"/' scripts/setlocalversion
5. $ make-kpkg clean
6. $ CONCURRENCY_LEVEL=`getconf _NPROCESSORS_ONLN` fakeroot \
      make-kpkg --initrd --append-to-version=-xia --revision=05 \
      kernel_image kernel_headers
```
#### Snapshot:

Kernel compiling error is caused by multiple definition of `sk_stream_alloc_skb':

![xia_compliling_error](https://cloud.githubusercontent.com/assets/7075154/5001485/38055478-69c4-11e4-8f3f-e7072e658c1d.png)

As far as I know, we have a lot of solutions to this error, such as modifying Makefile, changing struct name or adding #ifdef to avoid this, but I am not sure which one is optimal. Also, one truth is that we will finally have XIA-only networks without IP stack, so this is not a severe issue.

**Comment by AltraMayor** [comment]
Hi @BigQNo2,

Thank you for your detailed report.

I've decide to rename sk_stream_alloc_skb() to serval_sk_stream_alloc_skb() to solve this issue. I already pushed the code to the repository.
