### ISSUE TITLE
Missing include statement in fib.c

### ISSUE THREAD

**Issue by aaro1996** [AltraMayor/XIA-for-Linux#9]
In xia/net/xia/fib.c the function vmalloc from vmalloc.h is used on line 129, but there is no include statement for vmalloc in the header.  This was causing an error while compiling, but by adding #include < linux/vmalloc.h > the issue was solved.
![image](https://cloud.githubusercontent.com/assets/11033513/6217093/50790b92-b5de-11e4-9cc3-bec6bb02bcd9.png)

**Comment by AltraMayor** [comment]
Hi @aaro1996,

Thank you for your report. I've patched and pushed the code to GitHub.
